import React from 'react';

const About = () => {
    return (
        <div className='page_wrapper'>
            <div className='container'>
                <h1 className='brogAbout'>So, what is THE BROG all about?</h1>
                <p className='aboutFont'> 
                    Well, I am going to tell you right now. But first, I'm going to set the record straight... I am not a writer. Realistically, I should probably start doing a podcast or some shit cause I love to talk. Especially about technology. ** Note on language -- I will sometimes be using 'bad words'. This is my blog, I want to connect with people that want to get the authentic me. **  But yes, talking about technology is one of the many reasons I wanted to create a blog about JavaScript, my coding bootcamp experience, and how MY career change is going. Whenever I talk to my friends about programming, they have no flippin idea what I am talking about. And quite frankly, that stinks. I just want to tell someone about all the cool new tricks and tips that I am learning, and receive a response from them other than 'I don’t know what the hell you are talking about.’  So ya, that is a reason I really want to do this. If I can help one person out that is currently learning how to code, or wants to make a career change, then this was a huge success.  
                </p>
                <h2 className='brogAboutMe'>About me</h2>
                <p className='aboutFont'>
                    I'm Brad Donakowski, and I live in Denver, CO, born and raised. Currently, I am looking for a new role in Software Development. I finished a bootcamp in December of 2019. I can give you a quick rundown of my career so far, so you have an idea of why I decided to make the career change into software development. Soooo, During college I really had no idea what I wanted to do. Even post college, I still didn't Know. <strong>UNTIL</strong> I was introduced to coding. I really wish I knew that I enjoyed software development this much while I was attending college.. but, Oh well. It was all a great experience and having a degree in Management, could be very helpful since I would love to lead a team someday. I graduated from University of Northern Colorado during the Summer of 2017 with a degree in Business Management. I broke my knee shortly after, (Long story short, a golf cart flipped on me). I then got my first job out of school as an Account Manager with a company by the name of Apex Systems.  Apex Systems introduced me to the crazy world of tech. At first I had no idea what back-end and front-end development was or 'full stack' development, I didn't know there was a difference between JavaScript and Java. I was a complete noob when it came to tech, so I wanted to learn more about this just because it sounded really cool. I began to teach myself the basics with HTML and CSS, and I thought it was badass to see how a webpage is really made. I left Apex on April Fools day, what a weird day to quit, huh? But as I was saying, I left Apex to enroll in a coding bootcamp that was starting soon. At this point, I had been thinking about attending a bootcamp for about 8 months. It was such a huge decision because I felt there was a lot of uncertainty, mixed reviews, etc. I wanted to make sure I made the best decision for myself, so I took my time to pull the trigger. Of course, sometimes, things don't go as planned, and I got a call from a startup a week after I quit Apex. This startup was called Pax8, and they sold a variety of software products. I could not turn this opportunity down, because I have always wanted to be a part of a startup. Working there was great, but I realized I was in the wrong role, and still had the gut feeling I needed to pursue software development. After a short stint with Pax8, which was an incredible opportunity, I finally took a leap of faith, and enrolled in the bootcamp. It was one of the best decisions I have made and one of the greatest experiences I have had in my life. I can truly say I love the process of learning programming, and I am so happy I made the decision to do so. For now, that is all you need to know about me. You will learn quite a bit through my posts! Thanks and I appreciate you checking out the BROG.
                </p>
                 
            </div>
            
        </div>
    );
};

export default About;